### ISSUE TITLE
Is there an Seurat obj we can download?

### ISSUE THREAD

**Issue by YichaoOU** [YosefLab/Thymus_CITE-seq#1]
Hello,

It seems this one is not working: `Full data set: http://s133.cs.berkeley.edu:9002/Results.html`

I'm wondering if there is an Seurat obj that contains the UMAP and cell type annotation info?

Thanks,
Yichao

**Comment by zoesteier** [comment]
Hi Yichao,
Thanks for writing and my apologies that I didn't see your message sooner! If you haven't already seen it, please check the vision session again since it should still be active. There were no Seurat objects used in this analysis, but you can find the anndata objects on zenodo (https://zenodo.org/doi/10.5281/zenodo.8102049) which contain annotations, UMAP coordinates, and additional data. You will also see a .csv file with pseudotime metadata.

Zoë
