### ISSUE TITLE
Is there a Python environment available to reproduce the results?

### ISSUE THREAD

**Issue by aclynch160** [YosefLab/Thymus_CITE-seq#2]
The code is a bit outdated, and SCVI no longer uses many of the commands used. It would be nice to have the specific environment/packages used to create the analysis, if possible, in order to reproduce it; It may not be possible as is.

**Comment by zoesteier** [comment]
You are correct that this analysis was conducted with an older version of totalVI prior to scvi-tools. Rather than trying to reproduce the old environment and packages, I strongly recommend using the latest version of scvi-tools for future CITE-seq analysis. You will find that the code is much more straightforward. You can find an example here: https://docs.scvi-tools.org/en/stable/tutorials/notebooks/multimodal/totalVI.html. Best of luck!

Zoë
